ROBOTIS-move/labelme

.gitignore
CHANGELOG.rst
labelme/__main__.py
labelme/app.py
labelme/cli/__init__.py
labelme/cli/class.yaml
labelme/cli/draw_object_label.py
labelme/cli/draw_segment_label.py
labelme/config/__init__.py
labelme/config/default_config.yaml
labelme/label_file.py
labelme/utils/__init__.py
labelme/utils/draw.py
labelme/widgets/unique_label_qlist_widget.py
package.xml
set_labelme_environment.sh

- segmentaion과 detection class에 대한 라벨링을 진행할 때 필요한 기능들 추가
- Ubuntu에 labelme 설치하는 스크립트 파일 추가
- 왼쪽 툴바에 `hideAll`, `showAll` 버튼 추가
- 이미지에 라벨링 할 task에 따라 라벨링 버튼 활성화 되는 기능 추가 (segmentation - polygon, detection - object-2d)
- 이미지 변환 코드 추가 (segmentation - `draw_segment_label.py`, detection - `draw_object_label.py`)
- segmentation, detection class 리스트 추가
- CHANGELOG.rst 추가

Modified labelme for labeling by ROBOTIS algorithm team

---

labelme/app.py
labelme/label_file.py
setup.py

- 왼쪽 툴바에 `create rectangle` 버튼 추가
- 라벨링을 완료하고 저장할 때 class type이 저장되지 않는 문제 해결
- json file 저장 시 `imageData`에 데이터를 저장하면서 파일 용량이 커지는 문제 해결

Fixed saving errors

---

labelme/cli/draw_segment_label.py
labelme/utils/__init__.py
labelme/utils/_io.py

- masked image를 변환하는 코드에 문제가 있어서 수정했습니다.
- 수정된 코드로 이미지 변환한 결과:

Modified label masking function

---

labelme/app.py
labelme/config/__init__.py
labelme/config/default_config.yaml
setup.py

- 변환 프로그램 실행 시 matplotlib 에러가 뜨는 문제 해결 (이슈: https://github.com/ROBOTIS-move/labelme/issues/4#issuecomment-1127109391)
- 라벨링 진행 시 라벨별로 색상 구분되어 polygon에 표기되는 색상 고정 (이슈: https://github.com/ROBOTIS-move/labelme/issues/4#issuecomment-1127117286)

Changed matplotlib version and default label colors

---

labelme/app.py
labelme/config/__init__.py
labelme/config/default_config.yaml
labelme/widgets/canvas.py

- 점을 생성하는 기능을 껐다 켰다 할 수 있는 기능 추가 (이슈: https://github.com/ROBOTIS-move/labelme/issues/4#issuecomment-1128342900)

Added mode selection function for add point to edge

---

.gitignore
CHANGELOG.rst
labelme/__main__.py
labelme/app.py
labelme/cli/__init__.py
labelme/cli/class.yaml
labelme/cli/draw_object_label.py
labelme/cli/draw_segment_label.py
labelme/config/__init__.py
labelme/config/default_config.yaml
labelme/label_file.py
labelme/utils/__init__.py
labelme/utils/_io.py
labelme/utils/draw.py
labelme/widgets/canvas.py
package.xml
set_labelme_environment.sh
setup.py

참고: https://github.com/ROBOTIS-move/tote_tools/issues/317
모든 패키지가 릴리즈 준비 완료된 상태이면 전 팀원을 리뷰어로 걸어주시면 감사드리겠습니다 :)

Bump to 4.1.0

---

labelme/app.py
labelme/config/default_config.yaml

- 동일한 클래스를 연속적으로 라벨링할 때 효율을 더 높이기 위해서 single class mode를 추가했습니다. (단축키: Ctrl + Shift + B)

Added single class mode

---

labelme/app.py
labelme/cli/class.yaml
labelme/cli/draw_object_label.py
labelme/cli/draw_segment_label.py
labelme/config/__init__.py
labelme/config/default_config.yaml
labelme/label_file.py

- [엘리베이터 버튼 segmentation 라벨링을 위한 클래스](https://docs.google.com/presentation/d/1oKFNzkRzs4DP2_CoSAOZ8mOeVtNjcGvciCaLNsyHcEE/edit#slide=id.g11b81c8a679_0_43) 추가 및 기존 카테고리명 변경 완료했습니다.
- 기존에 실외 데이터 라벨링에 사용하던 classType(`segmentation`, `object-2d`)에도 정상 동작 할 수 있도록 예외처리를 해두었습니다.
- 기존과 동일하게 이미지 폴더를 열었을 때 진행해야되는 라벨 구분에 따라 segmentation 이미지는 create polygons 버튼이, object 이미지는 'create rectangle' 버튼이 활성화 됩니다.
- 이미지가 배포되기 전 json 파일을 생성할 때 classType에 따라 class 목록에 표시되는 라벨 목록이 선택됩니다.
(classType 종류: `outdoor_segmentation`, `outdoor_detection`, `indoor_segmentation`)

Added category for elevator button segmentation

---

labelme/cli/class.yaml
labelme/config/default_config.yaml

- `outdoor detection`에 `신호등 세부 클래스` 및 `동물(강아지, 고양이 등)` class 추가했습니다.
- [ROBOTIS_GT_가이드_ver3 - Object 클래스](https://docs.google.com/presentation/d/1BvH1QluOmLp7D1N2Haz6MRQH12uTESoqlXKcNu9gBcQ/edit#slide=id.g11b81c8a679_0_1845)에도 해당 클래스 추가했습니다.

Added new detection class

---

labelme/shape.py
labelme/widgets/canvas.py

- edit mode에서 label을 드래그로 옮겼을 때 이미지 밖으로 선이 나가는 버그를 해결했습니다.
- 연관 이슈: https://github.com/ROBOTIS-move/labelme/issues/24

Modified moving label function in edit mode

---

labelme/app.py
labelme/config/__init__.py
labelme/config/default_config.yaml

- 라벨을 그릴 때 나오는 라인 색상을 `(0, 0, 255)`에서 `(192, 217, 0)`으로 변경했습니다.
(연관 이슈: https://github.com/ROBOTIS-move/labelme/issues/27)
- 라벨 우선순위 변경 시 색상이 남는 문제 해결했습니다.
(연관 이슈: https://github.com/ROBOTIS-move/labelme/issues/28)

Changed drawing line color and color visualization rules

---

labelme/app.py
labelme/config/__init__.py
labelme/config/default_config.yaml
labelme/widgets/canvas.py

- hide all, show all 기능에 대해 단축키 부여 (hide all: Ctrl+H, show all: Ctrl+G)
(연관 이슈: https://github.com/ROBOTIS-move/labelme/issues/30)
- 라벨 이동시 방향키를 사용했을 때 이동량이 너무 많아 move speed를 5.0에서 2.0으로 변경
(연관 이슈: https://github.com/ROBOTIS-move/labelme/issues/31)
- 마우스가 움직일 때마다 canvas가 repaint되어 세그멘테이션 작업시 일정 점 갯수 이상 넘어가면 많이 느려지는 현상을 해결
(연관 이슈: https://github.com/ROBOTIS-move/labelme/issues/33)

Added shortcuts for hide and show all

---

labelme/config/default_config.yaml

Signed-off-by: Dongyun Kim <kdy@robotis.com>
- 실내 Segmentation Class를 수정했습니다.

Changed the category name of indoor segmentation

---

labelme/app.py
labelme/config/__init__.py
labelme/config/default_config.yaml
labelme/widgets/canvas.py
labelme/widgets/label_dialog.py

- 특정 상황에서 일정 구역에 점 추가가 불가능한 문제를 해결했습니다.
(연관 이슈: https://github.com/ROBOTIS-move/labelme/issues/38)
- Label name list가 화면 밖을 벗어나지 않도록 수정했습니다.
(연관 이슈: https://github.com/ROBOTIS-move/labelme/issues/37)

Modified a popup position and Fixed a intersection point bug

---

labelme/app.py
labelme/config/__init__.py
labelme/config/default_config.yaml
labelme/widgets/brightness_contrast_dialog.py
labelme/widgets/label_dialog.py

- 변환된 이미지를 labelme 프로그램에서 확인할 수 없었던 문제를 해결했습니다.
- 듀얼모니터 사용 시 라벨 리스트 팝업창이 화면 밖으로 나가는 문제를 해결했습니다.
- `Open file`클릭 후 이미지를 선택하지 않고 취소 버튼을 누르면 프로그램이 비정상 종료되는 문제를 해결했습니다.
- 밝기 및 대비를 조절할 수 있는 옵션을 활성화하고 단축키를 `Ctrl+M`으로 설정했습니다.

Fixed minor bugs and Activated brightness and contrast options

---

CHANGELOG.rst

Signed-off-by: eungiCho <ceg@robotis.com>

Modified CHANGELOG.rst

---

labelme/cli/class.yaml
labelme/config/__init__.py
labelme/config/default_config.yaml

- 마이다스 호텔&리조트 데이터 라벨링을 위해 segmentation 라벨에 자갈(pebble) 클래스 추가했습니다.
- 참고: https://www.notion.so/robotis-move/f80c7323e4d54c148a40dca0dba9352d#fb828cd036fd4e0380c4b4b32fac5d9e

Added a new segmentation class

---

CHANGELOG.rst
examples/bbox_detection/data_dataset_voc/Annotations/2011_000025.xml
package.xml

참고: https://github.com/ROBOTIS-move/tote_tools/issues/368
모든 패키지가 릴리즈 준비 완료된 상태이면 전 팀원을 리뷰어로 걸어주시면 감사드리겠습니다 :)

Bump to 4.6.0

---

labelme/app.py
labelme/config/__init__.py
labelme/config/default_config.yaml
labelme/widgets/__init__.py
labelme/widgets/image_popup.py

- 이미지 검토를 더 쉽게 하기 위해 검토용 이미지를 팝업으로 띄우는 기능을 추가했습니다.
- 상단 메뉴의 `Administrator`-`Check Labels`를 누르면 기능이 활성화되며, 단축키는 `Ctrl+/` 입니다.
- 이미지 변환(`draw_segment_label.py`)이 되어있어야 팝업에 검토용 이미지가 팝업으로 뜨게 됩니다.
- 연관 이슈: https://github.com/ROBOTIS-move/labelme/issues/50

Added image pop-up function for review

---

labelme/app.py
labelme/cli/draw_object_label.py
labelme/cli/draw_segment_label.py
labelme/widgets/__init__.py
labelme/widgets/convert_label_popup.py
labelme/widgets/image_popup.py

- Detection 라벨 변환을 버튼 클릭으로 할 수 있게 기능을 추가했습니다. (기존 draw_object_label.py 실행과 동일한 기능)
- 변환시 뜨는 팝업에 변환 진행 상황을 알 수 있게 prograss bar를 추가했습니다.
- class type에 따라 `convert segmentation`과 `convert objects` 버튼이 활성화 됩니다.
- `Check labels` 버튼을 눌러서 detection 라벨도 이미지 팝업을 띄울 수 있습니다.

Modified administrator functions

---

labelme/app.py
labelme/config/__init__.py
labelme/config/default_config.yaml
labelme/widgets/canvas.py
set_labelme_environment.sh

- 방향키로 다음/이전 이미지를 불러올 수 있도록 단축키 추가했습니다.
- 박스 삭제 단축키에 `Q`를 추가했습니다. (기존에 사용하던 `delete` 키도 사용 가능)
- 박스 삭제 시 팝업창을 띄우지 않는 기능 및 해당 기능 사용을 선택할 수 있도록 추가했습니다.
(하단 이미지의 빨간색 박스, 단축키는 `Ctrl+Shift+Q` 입니다.)
- 박스 라벨의 우측 하단 포인트를 단축키로 이동시킬 수 있도록 기능을 추가했습니다.
(1: 위로 이동, 2: 아래로 이동, 3: 왼쪽으로 이동, 4: 오른쪽으로 이동)
- 박스를 클릭한 뒤 단축키 `E`를 누르면 클래스 변경 팝업이 뜰 수 있게 기능을 추가했습니다. (하단 이미지의 파란색 박스)
- 연관 이슈: https://github.com/ROBOTIS-move/labelme/issues/54

Added useful functions for detection labeling

---

CHANGELOG.rst
examples/bbox_detection/data_dataset_voc/Annotations/2011_000006.xml
package.xml

참고: https://github.com/ROBOTIS-move/tote_tools/issues/379
모든 패키지가 릴리즈 준비 완료된 상태이면 전 팀원을 리뷰어로 걸어주시면 감사드리겠습니다 :)

Bump to 4.8.0

---

labelme/app.py
labelme/config/__init__.py

- 비정상적 json 파일 생성 이슈(#64)에 대응하기 위해 Delete file 버튼을 비활성화 했습니다.

Deactivated delete file button

---

CHANGELOG.rst

bump 4.9.0을 위해 CHANGELOG.rst를 수정했습니다

Edited CHANGELOG.rst for bump

---

CHANGELOG.rst
examples/bbox_detection/data_dataset_voc/Annotations/2011_000025.xml
package.xml

참고: https://github.com/ROBOTIS-move/tote_tools/issues/389
모든 패키지가 릴리즈 준비 완료된 상태이면 전 팀원을 리뷰어로 걸어주시면 감사드리겠습니다 :)

Bump to 4.10.0

---

CHANGELOG.rst

- 4.11.0 버전 릴리즈를 위해 CHANGELOG.rst를 수정했습니다.
Signed-off-by: jongsuff <yujs@robotis.com>

Modified CHANGELOG.rst for bump 4.11.0

---

CHANGELOG.rst
package.xml

참고: https://github.com/ROBOTIS-move/tote_tools/issues/402

Bump to 5.0.0

---

CHANGELOG.rst

Bump를 위해 CHANGELOG.rst를 업데이트 했습니다.

Updated CHANGELOG

---

CHANGELOG.rst
package.xml

참고: https://github.com/ROBOTIS-move/tote_tools/issues/426

Bump to 5.4.0

---

labelme/app.py
labelme/config/__init__.py

- config파일에 특정 ```service area```에 대한 클래스 리스트 정보가 없으면 ```default```로 세팅하도록 예외처리 하였습니다.

Added setting service area as default if certain area not in config

---

CHANGELOG.rst

Updated CHANGELOG for 5.5.0

---

CHANGELOG.rst
package.xml

참고: https://github.com/ROBOTIS-move/tote_tools/issues/433

Bump to 5.6.0

---

labelme/cli/class.yaml
labelme/config/__init__.py
labelme/config/default_config.yaml

- Segmentation 의 non-target 클래스들을 추가하였습니다.

Added segmentation non-target class info

---

CHANGELOG.rst
package.xml

참고: https://github.com/ROBOTIS-move/tote_tools/issues/445

Bump to 5.8.0

---

labelme/cli/class.yaml
labelme/config/__init__.py
labelme/config/default_config.yaml

- `docking-station` 클래스를 추가하였습니다.
- 정선 하이원 CC 라벨링을 위해 default 에 클래스들을 추가하였습니다.

Added new segmentation class

---

CHANGELOG.rst
package.xml

참고: https://github.com/ROBOTIS-move/tote_tools/issues/459

Bump to 5.10.0

---

CHANGELOG.rst
package.xml

참고: https://github.com/ROBOTIS-move/tote_tools/issues/476

Bump to 5.13.0

---

labelme/cli/class.yaml
labelme/config/__init__.py
labelme/config/default_config.yaml
labelme/widgets/label_dialog.py

Changed vehicle color

---

labelme/app.py
labelme/config/__init__.py
labelme/utils/measure_working_time.py
labelme/widgets/worker_name_dialog.py

특정 PC에서 발생하는 버그 수정
- Config File 읽을 때 utf-8로 코덱을 지정하여 읽을 수 있도록 수정
- worker_name 파일 읽을 때 os 환경에 따라서 '/', '\\' 를 선택해서 사용하도록 수정
Indoor 작업에서 Point size가 지나치게 작던 부분 수정

Fixed bugs of opening config file and worker_name file

---

labelme/app.py
labelme/config/__init__.py
labelme/config/default_config.yaml
labelme/shape.py
labelme/utils/measure_working_time.py
labelme/widgets/canvas.py
labelme/widgets/label_dialog.py
package.xml

- 기능 추가 요청사항(https://github.com/ROBOTIS-move/labelme/issues/110) 에 대응하기 위한 작업을 진행했습니다.
- 기존에 박스를 수정할 때 박스 꼭짓점들 중 `좌상단/우하단` 꼭짓점만 수정가능한 상태였으나, `우상단/좌하단` 꼭짓점으로도 수정할 수 있도록 기능을 추가했습니다.
- 새로운 `우상단/좌하단` 꼭짓점은 박스 수정시에만 사용되며, json파일 내 데이터는 기존과 동일하게 `좌상단/우하단` 좌표만 저장됩니다.
- 계산된 라벨러 작업 시간이 저장되는 cache파일에 작업자 이름에 대한 정보가 누락되어 해당 정보를 저장하는 기능을 추가하였습니다(by @DongyunRobotis).
- 라벨러 작업 시간 계산에 microsecond까지 계산되도록 수정하였습니다(by @DongyunRobotis).

Added editing bounding box size with top right and bottom left corner and fixed bug in measuring working time

---

CHANGELOG.rst
package.xml

참고: https://github.com/ROBOTIS-move/tote_tools/issues/494

Bump to 5.18.0

---

labelme/app.py
labelme/cli/draw_object_label.py
labelme/cli/draw_segment_label.py
labelme/config/__init__.py
labelme/config/default_config.yaml
labelme/shape.py
labelme/utils/__init__.py
labelme/utils/_io.py
labelme/utils/draw.py
labelme/utils/measure_working_time.py
labelme/utils/version_checker.py
labelme/widgets/__init__.py
labelme/widgets/canvas.py
labelme/widgets/image_popup.py
labelme/widgets/invalid_version_popup.py
labelme/widgets/worker_name_dialog.py
setup.py
version.xml

**기능 추가 및 개선**
**1. Labelme 최신 버전 체크 기능**
- 동작 방식: Labelme GitHub develop repository에서 version.xml 파일을 읽어와 현재 로컬에 설치된 Labelme의 version.xml 파일 버전과 비교합니다.
- 버전 불일치 시: Version Checker 팝업이 활성화되며, 확인 버튼을 누르면 Labelme가 종료되어 추가 작업이 불가능합니다.
- 인터넷 미연결 시: 인터넷 연결을 요청하는 팝업이 활성화됩니다.
**2. 작업량 로그 저장 시점 추가**
- 이전 이미지로 돌아가서 작업하는 경우: 해당 시점의 작업량 로그를 저장합니다.
- 작업 도중 Labelme 프로그램을 종료하는 경우: 프로그램 종료 시점의 작업량 로그를 저장합니다.
**3. Segmentation Polygon Label 정보 표시 기능 추가**
- Polygon Label을 볼 수 있도록 polygon 무게중심에 label 데이터를 표시 합니다.
**4. Drawing 관련 수정**
- 실내 라벨링 중 Polygon과 Box 데이터가 공존하는 경우 둘다 그리기 및 수정이 가능합니다.
**5. 기타**
- Lint 문법에 맞춰 코드가 수정 되었습니다.
**6. 참고사항**
- 테스트를 위해서 **labelme/utils/version_checker.py** 파일에서 self.url = 'https://raw.githubusercontent.com/ROBOTIS-move/labelme/**develop**/version.xml' 코드에서 develop 부분을 …

Added Version Checker and Enhanced Logging for Labelme

---

labelme/app.py
version.xml

- Edit 후 새로 도형을 생성하는 과정에서 Segmentation과 Detection이 반대로 활성화 되는 부분을 수정하였습니다.

Fix bug where rectangle and polygon were set inversely in the edit stage

---

CHANGELOG.rst

- Bump 5.24.0을 위해 CHANGELOG.rst 업데이트

Updated CHANGELOG.rst for bump

---

CHANGELOG.rst
package.xml

참고: https://github.com/ROBOTIS-move/tote_tools/issues/528

Bump to 5.25.0

---

package.xml
version.xml

* bump to develop branch for upcoming version
* Update Package version file
---
* 로컬 개발 환경에서 테스트 완료
---
* https://github.com/ROBOTIS-move/labelme/pull/131

[Bump] 5.28.0 to develop for upcoming feature

---

examples/bbox_detection/data_annotated/2011_000003.json
examples/bbox_detection/data_annotated/2011_000006.json
examples/bbox_detection/data_annotated/2011_000025.json
examples/classification/data_annotated/0001.json
examples/classification/data_annotated/0002.json
examples/instance_segmentation/data_annotated/2011_000003.json
examples/instance_segmentation/data_annotated/2011_000006.json
examples/instance_segmentation/data_annotated/2011_000025.json
examples/primitives/primitives.json
examples/semantic_segmentation/data_annotated/2011_000003.json
examples/semantic_segmentation/data_annotated/2011_000006.json
examples/semantic_segmentation/data_annotated/2011_000025.json
examples/tutorial/apc2016_obj3.json
examples/video_annotation/data_annotated/00000100.json
examples/video_annotation/data_annotated/00000101.json
examples/video_annotation/data_annotated/00000102.json
examples/video_annotation/data_annotated/00000103.json
examples/video_annotation/data_annotated/00000104.json
package.xml
version.xml

* bump to develop branch for upcoming version
* Update Package version file
---
* 로컬 개발 환경에서 테스트 완료
---
* https://github.com/ROBOTIS-move/labelme/pull/134

[Bump] 5.29.0 to develop for upcoming feature

---

examples/bbox_detection/data_annotated/2011_000003.json
examples/bbox_detection/data_annotated/2011_000006.json
examples/bbox_detection/data_annotated/2011_000025.json
examples/classification/data_annotated/0001.json
examples/classification/data_annotated/0002.json
examples/instance_segmentation/data_annotated/2011_000003.json
examples/instance_segmentation/data_annotated/2011_000006.json
examples/instance_segmentation/data_annotated/2011_000025.json
examples/primitives/primitives.json
examples/semantic_segmentation/data_annotated/2011_000003.json
examples/semantic_segmentation/data_annotated/2011_000006.json
examples/semantic_segmentation/data_annotated/2011_000025.json
examples/tutorial/apc2016_obj3.json
examples/video_annotation/data_annotated/00000100.json
examples/video_annotation/data_annotated/00000101.json
examples/video_annotation/data_annotated/00000102.json
examples/video_annotation/data_annotated/00000103.json
examples/video_annotation/data_annotated/00000104.json
package.xml
version.xml

* bump to develop branch for upcoming version
* Update Package version file
---
* 로컬 개발 환경에서 테스트 완료
---
* https://github.com/ROBOTIS-move/labelme/pull/137

[Bump] 5.30.0 to develop for upcoming feature
